/**
 * Local thumbnail resolution (MISSION-017). The manifest is generated by
 * scripts/build-thumbs.mjs from the committed fixtures — a baked 480px WebP
 * beats shipping the full-resolution original into a 240px card by ~10x.
 * No fs at runtime (the Worker has none): the manifest is imported JSON.
 */

import baked from '../generated/local-thumbs.json';

const LOCAL = new Set<string>(baked as string[]);

/** The 480px local WebP when baked; the remote original otherwise. */
export function thumbSrc(assetId: string, remoteUrl: string | null): string | null {
  if (LOCAL.has(assetId)) return `/thumbs/${assetId}.webp`;
  return remoteUrl;
}
